version: '3.8'

services:
  pos-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos-service
    ports:
      - "8021:8021"
    environment:
      - spring_profiles_active=development
    networks:
      - consul_consul

networks:
  consul_consul:
    external: true
