server:
  port: 8080

spring:
  application:
    name: USER-SERVICE
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: USER-SERVICE
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s

  datasource:
    url: jdbc:postgresql://localhost:5432/acedemix
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
