server:
  port: 8080

spring:
  application:
    name: USER-SERVICE
  cloud:
    consul:
      host: localhost
      port: 9000
      discovery:
        service-name: USER-SERVICE
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s

  datasource:
    url: jdbc:postgresql://localhost:5432/acedemix
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mybatis:
    type-aliases-package: com.userservice.api.user.model.table
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
