

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=acedemix'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
    networks:
      - academix-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  consul:
    image: 'consul:1.15.4'
    container_name: 'consul-server'
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    networks:
      - academix-net



volumes:
  postgres-data:


networks:
  academix-net:
    driver: bridge
